apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-jupyterhub
  namespace: jupyterhub
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "fb7ae447-5716-48e7-8657-78ffe30bba5f"
    keyvaultName: "kv-sreproject-dr-01"
    tenantId: "c48072c6-ee14-4db6-ac11-94cddbf4b6ed"
    objects: |
      array:
        - |
          objectName: jupyterhub-db-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: jupyterhub-db-host
          objectType: secret
          objectVersion: ""
        - |
          objectName: jupyterhub-db-username
          objectType: secret
          objectVersion: ""
        - |
          objectName: jupyterhub-db-name
          objectType: secret
          objectVersion: ""
        - |
          objectName: jupyterhub-db-port
          objectType: secret
          objectVersion: ""
        - |
          objectName: jupyterhub-db-url
          objectType: secret
          objectVersion: ""
        - |
          objectName: jupyterhub-oauth-client-id
          objectType: secret
          objectVersion: ""
        - |
          objectName: jupyterhub-oauth-client-secret
          objectType: secret
          objectVersion: ""
        - |
          objectName: jupyterhub-proxy-secret-token
          objectType: secret
          objectVersion: ""
  secretObjects:
  - secretName: jupyterhub-secrets
    type: Opaque
    data:
    - objectName: jupyterhub-db-password
      key: hub.db.password
    - objectName: jupyterhub-db-url
      key: hub.db.url
    - objectName: jupyterhub-proxy-secret-token
      key: proxy.secretToken
    - objectName: jupyterhub-oauth-client-id
      key: oauth-client-id
    - objectName: jupyterhub-oauth-client-secret
      key: oauth-client-secret
  - secretName: jupyterhub-db
    type: Opaque
    data:
    - objectName: jupyterhub-db-host
      key: db-host
    - objectName: jupyterhub-db-username
      key: db-username
    - objectName: jupyterhub-db-name
      key: db-name
    - objectName: jupyterhub-db-port
      key: db-port
    - objectName: jupyterhub-db-password
      key: db-password
    - objectName: jupyterhub-db-url
      key: db-url
