apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app

resources:
  - secrets.yaml
  - configmap.yaml
  - frontend-api.yaml
  - business-logic.yaml
  - data-ingest.yaml
  - microservices-ingress.yaml

labels:
  - pairs:
      environment: dr
      managed-by: kustomize

# Add common annotations
commonAnnotations:
  deployment.region: "dr"
  deployment.tool: "kustomize"
