apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

resources:
- namespace.yaml
- network-policy.yaml
- secret.yaml
- configmap.yaml
- service.yaml
- statefulset.yaml
- secret-provider-class.yaml

commonLabels:
  app.kubernetes.io/name: postgresql
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: multi-region-dr
  environment: dr
