apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    name: database
    app.kubernetes.io/name: database
    app.kubernetes.io/component: data-layer
    app.kubernetes.io/part-of: multi-region-dr
    environment: production
