apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-postgresql
  namespace: database
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "fb7ae447-5716-48e7-8657-78ffe30bba5f"
    keyvaultName: "kv-sreproject-dr-01"
    tenantId: "c48072c6-ee14-4db6-ac11-94cddbf4b6ed"
    objects: |
      array:
        - |
          objectName: postgresql-password
          objectType: secret
          objectVersion: ""
        - |
          objectName: postgresql-replication-password
          objectType: secret
          objectVersion: ""
  secretObjects:
  - secretName: postgresql-secret
    type: Opaque
    data:
    - objectName: postgresql-password
      key: postgres-password
    - objectName: postgresql-replication-password
      key: replication-password
